plugins:
  - jekyll-seo-tag

name: Alex S. Dawkins
logo: https://github.com/ouked.png
tagline: is this thing on?
description: A personal website for writing about previous projects.
url: https://alex-dawkins.com
author: Alex S. Dawkins
locale: en_GB
github: https://github.com/ouked
email: mailto:alexander.dawkins@gmail.com?subject=Enquiry%20(Personal%20Website)
linkedin: https://www.linkedin.com/in/alexsdawkins/
github_username: ouked
social:
  name: Alex Dawkins
  links:
    - https://www.linkedin.com/in/alexsdawkins/
    - https://github.com/ouked
cv: files/alex_dawkins_public_cv.pdf
