name: Alex S. Dawkins

logo: https://github.com/ouked.png?size=128
tagline: is this thing on?
github: https://github.com/ouked
email: mailto:asd60@bath.ac.uk?subject=Enquiry%20(Personal%20Website)
linkedin: https://www.linkedin.com/in/alexsdawkins/
